/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FieldFormImport } from './routes/field-form'
import { Route as EventFormImport } from './routes/event-form'
import { Route as DebouncedFieldImport } from './routes/debounced-field'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FieldFormRoute = FieldFormImport.update({
  id: '/field-form',
  path: '/field-form',
  getParentRoute: () => rootRoute,
} as any)

const EventFormRoute = EventFormImport.update({
  id: '/event-form',
  path: '/event-form',
  getParentRoute: () => rootRoute,
} as any)

const DebouncedFieldRoute = DebouncedFieldImport.update({
  id: '/debounced-field',
  path: '/debounced-field',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/debounced-field': {
      id: '/debounced-field'
      path: '/debounced-field'
      fullPath: '/debounced-field'
      preLoaderRoute: typeof DebouncedFieldImport
      parentRoute: typeof rootRoute
    }
    '/event-form': {
      id: '/event-form'
      path: '/event-form'
      fullPath: '/event-form'
      preLoaderRoute: typeof EventFormImport
      parentRoute: typeof rootRoute
    }
    '/field-form': {
      id: '/field-form'
      path: '/field-form'
      fullPath: '/field-form'
      preLoaderRoute: typeof FieldFormImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debounced-field': typeof DebouncedFieldRoute
  '/event-form': typeof EventFormRoute
  '/field-form': typeof FieldFormRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debounced-field': typeof DebouncedFieldRoute
  '/event-form': typeof EventFormRoute
  '/field-form': typeof FieldFormRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/debounced-field': typeof DebouncedFieldRoute
  '/event-form': typeof EventFormRoute
  '/field-form': typeof FieldFormRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debounced-field' | '/event-form' | '/field-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debounced-field' | '/event-form' | '/field-form'
  id: '__root__' | '/' | '/debounced-field' | '/event-form' | '/field-form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebouncedFieldRoute: typeof DebouncedFieldRoute
  EventFormRoute: typeof EventFormRoute
  FieldFormRoute: typeof FieldFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebouncedFieldRoute: DebouncedFieldRoute,
  EventFormRoute: EventFormRoute,
  FieldFormRoute: FieldFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/debounced-field",
        "/event-form",
        "/field-form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/debounced-field": {
      "filePath": "debounced-field.tsx"
    },
    "/event-form": {
      "filePath": "event-form.tsx"
    },
    "/field-form": {
      "filePath": "field-form.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
