/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PasswordImport } from './routes/password'
import { Route as FieldFormImport } from './routes/field-form'
import { Route as EventFormImport } from './routes/event-form'
import { Route as DebouncedFieldImport } from './routes/debounced-field'
import { Route as AddressImport } from './routes/address'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PasswordRoute = PasswordImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRoute,
} as any)

const FieldFormRoute = FieldFormImport.update({
  id: '/field-form',
  path: '/field-form',
  getParentRoute: () => rootRoute,
} as any)

const EventFormRoute = EventFormImport.update({
  id: '/event-form',
  path: '/event-form',
  getParentRoute: () => rootRoute,
} as any)

const DebouncedFieldRoute = DebouncedFieldImport.update({
  id: '/debounced-field',
  path: '/debounced-field',
  getParentRoute: () => rootRoute,
} as any)

const AddressRoute = AddressImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressImport
      parentRoute: typeof rootRoute
    }
    '/debounced-field': {
      id: '/debounced-field'
      path: '/debounced-field'
      fullPath: '/debounced-field'
      preLoaderRoute: typeof DebouncedFieldImport
      parentRoute: typeof rootRoute
    }
    '/event-form': {
      id: '/event-form'
      path: '/event-form'
      fullPath: '/event-form'
      preLoaderRoute: typeof EventFormImport
      parentRoute: typeof rootRoute
    }
    '/field-form': {
      id: '/field-form'
      path: '/field-form'
      fullPath: '/field-form'
      preLoaderRoute: typeof FieldFormImport
      parentRoute: typeof rootRoute
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/debounced-field': typeof DebouncedFieldRoute
  '/event-form': typeof EventFormRoute
  '/field-form': typeof FieldFormRoute
  '/password': typeof PasswordRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/debounced-field': typeof DebouncedFieldRoute
  '/event-form': typeof EventFormRoute
  '/field-form': typeof FieldFormRoute
  '/password': typeof PasswordRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/debounced-field': typeof DebouncedFieldRoute
  '/event-form': typeof EventFormRoute
  '/field-form': typeof FieldFormRoute
  '/password': typeof PasswordRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address'
    | '/debounced-field'
    | '/event-form'
    | '/field-form'
    | '/password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address'
    | '/debounced-field'
    | '/event-form'
    | '/field-form'
    | '/password'
  id:
    | '__root__'
    | '/'
    | '/address'
    | '/debounced-field'
    | '/event-form'
    | '/field-form'
    | '/password'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRoute: typeof AddressRoute
  DebouncedFieldRoute: typeof DebouncedFieldRoute
  EventFormRoute: typeof EventFormRoute
  FieldFormRoute: typeof FieldFormRoute
  PasswordRoute: typeof PasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
  DebouncedFieldRoute: DebouncedFieldRoute,
  EventFormRoute: EventFormRoute,
  FieldFormRoute: FieldFormRoute,
  PasswordRoute: PasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/address",
        "/debounced-field",
        "/event-form",
        "/field-form",
        "/password"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/address": {
      "filePath": "address.tsx"
    },
    "/debounced-field": {
      "filePath": "debounced-field.tsx"
    },
    "/event-form": {
      "filePath": "event-form.tsx"
    },
    "/field-form": {
      "filePath": "field-form.tsx"
    },
    "/password": {
      "filePath": "password.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
