name: CI / React

on:
    push:

env:
    HUSKY: 0

jobs:
    commit-checks:
        runs-on: ubuntu-latest
        name: pre-commit-js
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v4.4.0
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
                  check-latest: true

            - name: Install dependencies
              run: pnpm i

            - name: Run lint
              run: |
                  if [ ! -f .env.local ]; then 
                      cp .env.template .env.local;
                  fi
                  pnpm run lint

            - name: Run type checks
              run: pnpm lint:types

            - name: Check for any diffs
              run: git diff --exit-code

            - name: Comment on Summary if `F`ailure
              if: ${{ failure() }}
              run: |
                  echo "Lint checks failed. Please review and fix the issues." | tee -a ${GITHUB_STEP_SUMMARY}
